# For available configuration options, see:
#   https://github.com/testdouble/standard

default_ignores: false
format: progress
fix: true
parallel: true
ignore:
  - 'db/schema.rb'
  - 'vendor/**/*'
  - 'test/**/*':
    - Layout/AlignHash
